// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: field.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FieldDefinition with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FieldDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FieldDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FieldDefinitionMultiError, or nil if none found.
func (m *FieldDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *FieldDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for IsPrimary

	// no validation rules for Repeated

	for idx, item := range m.GetFields() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FieldDefinitionValidationError{
						field:  fmt.Sprintf("Fields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FieldDefinitionValidationError{
						field:  fmt.Sprintf("Fields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FieldDefinitionValidationError{
					field:  fmt.Sprintf("Fields[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	switch m.DataType.(type) {

	case *FieldDefinition_Scalar:
		// no validation rules for Scalar

	case *FieldDefinition_Geo:
		// no validation rules for Geo

	}

	if len(errors) > 0 {
		return FieldDefinitionMultiError(errors)
	}

	return nil
}

// FieldDefinitionMultiError is an error wrapping multiple validation errors
// returned by FieldDefinition.ValidateAll() if the designated constraints
// aren't met.
type FieldDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FieldDefinitionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FieldDefinitionMultiError) AllErrors() []error { return m }

// FieldDefinitionValidationError is the validation error returned by
// FieldDefinition.Validate if the designated constraints aren't met.
type FieldDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FieldDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FieldDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FieldDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FieldDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FieldDefinitionValidationError) ErrorName() string { return "FieldDefinitionValidationError" }

// Error satisfies the builtin error interface
func (e FieldDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFieldDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FieldDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FieldDefinitionValidationError{}
