// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: segment.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*SegmentField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *Segment) Reset() {
	*x = Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetFields() []*SegmentField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SegmentField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//	*SegmentField_StringValue
	//	*SegmentField_RepeatedStringValue
	//	*SegmentField_IntValue
	//	*SegmentField_RepeatedIntValue
	//	*SegmentField_UintValue
	//	*SegmentField_RepeatedUintValue
	//	*SegmentField_FloatValue
	//	*SegmentField_RepeatedFloatValue
	//	*SegmentField_BoolValue
	//	*SegmentField_RepeatedBoolValue
	//	*SegmentField_BlobValue
	//	*SegmentField_RepeatedBlobValue
	//	*SegmentField_RangeIntValue
	//	*SegmentField_RepeatedRangeIntValue
	//	*SegmentField_RangeFloatValue
	//	*SegmentField_RepeatedRangeFloatValue
	//	*SegmentField_GeoPointValue
	//	*SegmentField_RepeatedGeoPointValue
	//	*SegmentField_GeoRectValue
	//	*SegmentField_RepeatedGeoRectValue
	Value isSegmentField_Value `protobuf_oneof:"value"`
}

func (x *SegmentField) Reset() {
	*x = SegmentField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentField) ProtoMessage() {}

func (x *SegmentField) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentField.ProtoReflect.Descriptor instead.
func (*SegmentField) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{1}
}

func (x *SegmentField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *SegmentField) GetValue() isSegmentField_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *SegmentField) GetStringValue() *SegmentFieldString {
	if x, ok := x.GetValue().(*SegmentField_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedStringValue() *SegmentFieldRepeatedString {
	if x, ok := x.GetValue().(*SegmentField_RepeatedStringValue); ok {
		return x.RepeatedStringValue
	}
	return nil
}

func (x *SegmentField) GetIntValue() *SegmentFieldInt {
	if x, ok := x.GetValue().(*SegmentField_IntValue); ok {
		return x.IntValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedIntValue() *SegmentFieldRepeatedInt {
	if x, ok := x.GetValue().(*SegmentField_RepeatedIntValue); ok {
		return x.RepeatedIntValue
	}
	return nil
}

func (x *SegmentField) GetUintValue() *SegmentFieldUInt {
	if x, ok := x.GetValue().(*SegmentField_UintValue); ok {
		return x.UintValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedUintValue() *SegmentFieldRepeatedUInt {
	if x, ok := x.GetValue().(*SegmentField_RepeatedUintValue); ok {
		return x.RepeatedUintValue
	}
	return nil
}

func (x *SegmentField) GetFloatValue() *SegmentFieldFloat {
	if x, ok := x.GetValue().(*SegmentField_FloatValue); ok {
		return x.FloatValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedFloatValue() *SegmentFieldRepeatedFloat {
	if x, ok := x.GetValue().(*SegmentField_RepeatedFloatValue); ok {
		return x.RepeatedFloatValue
	}
	return nil
}

func (x *SegmentField) GetBoolValue() *SegmentFieldBool {
	if x, ok := x.GetValue().(*SegmentField_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedBoolValue() *SegmentFieldRepeatedBool {
	if x, ok := x.GetValue().(*SegmentField_RepeatedBoolValue); ok {
		return x.RepeatedBoolValue
	}
	return nil
}

func (x *SegmentField) GetBlobValue() *SegmentFieldBlob {
	if x, ok := x.GetValue().(*SegmentField_BlobValue); ok {
		return x.BlobValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedBlobValue() *SegmentFieldRepeatedBlob {
	if x, ok := x.GetValue().(*SegmentField_RepeatedBlobValue); ok {
		return x.RepeatedBlobValue
	}
	return nil
}

func (x *SegmentField) GetRangeIntValue() *SegmentFieldRangeInt {
	if x, ok := x.GetValue().(*SegmentField_RangeIntValue); ok {
		return x.RangeIntValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedRangeIntValue() *SegmentFieldRepeatedRangeInt {
	if x, ok := x.GetValue().(*SegmentField_RepeatedRangeIntValue); ok {
		return x.RepeatedRangeIntValue
	}
	return nil
}

func (x *SegmentField) GetRangeFloatValue() *SegmentFieldRangeFloat {
	if x, ok := x.GetValue().(*SegmentField_RangeFloatValue); ok {
		return x.RangeFloatValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedRangeFloatValue() *SegmentFieldRepeatedRangeFloat {
	if x, ok := x.GetValue().(*SegmentField_RepeatedRangeFloatValue); ok {
		return x.RepeatedRangeFloatValue
	}
	return nil
}

func (x *SegmentField) GetGeoPointValue() *SegmentFieldGeoPoint {
	if x, ok := x.GetValue().(*SegmentField_GeoPointValue); ok {
		return x.GeoPointValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedGeoPointValue() *SegmentFieldRepeatedGeoPoint {
	if x, ok := x.GetValue().(*SegmentField_RepeatedGeoPointValue); ok {
		return x.RepeatedGeoPointValue
	}
	return nil
}

func (x *SegmentField) GetGeoRectValue() *SegmentFieldGeoRect {
	if x, ok := x.GetValue().(*SegmentField_GeoRectValue); ok {
		return x.GeoRectValue
	}
	return nil
}

func (x *SegmentField) GetRepeatedGeoRectValue() *SegmentFieldRepeatedGeoRect {
	if x, ok := x.GetValue().(*SegmentField_RepeatedGeoRectValue); ok {
		return x.RepeatedGeoRectValue
	}
	return nil
}

type isSegmentField_Value interface {
	isSegmentField_Value()
}

type SegmentField_StringValue struct {
	StringValue *SegmentFieldString `protobuf:"bytes,10,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type SegmentField_RepeatedStringValue struct {
	RepeatedStringValue *SegmentFieldRepeatedString `protobuf:"bytes,11,opt,name=repeated_string_value,json=repeatedStringValue,proto3,oneof"`
}

type SegmentField_IntValue struct {
	IntValue *SegmentFieldInt `protobuf:"bytes,20,opt,name=int_value,json=intValue,proto3,oneof"`
}

type SegmentField_RepeatedIntValue struct {
	RepeatedIntValue *SegmentFieldRepeatedInt `protobuf:"bytes,21,opt,name=repeated_int_value,json=repeatedIntValue,proto3,oneof"`
}

type SegmentField_UintValue struct {
	UintValue *SegmentFieldUInt `protobuf:"bytes,30,opt,name=uint_value,json=uintValue,proto3,oneof"`
}

type SegmentField_RepeatedUintValue struct {
	RepeatedUintValue *SegmentFieldRepeatedUInt `protobuf:"bytes,31,opt,name=repeated_uint_value,json=repeatedUintValue,proto3,oneof"`
}

type SegmentField_FloatValue struct {
	FloatValue *SegmentFieldFloat `protobuf:"bytes,40,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type SegmentField_RepeatedFloatValue struct {
	RepeatedFloatValue *SegmentFieldRepeatedFloat `protobuf:"bytes,41,opt,name=repeated_float_value,json=repeatedFloatValue,proto3,oneof"`
}

type SegmentField_BoolValue struct {
	BoolValue *SegmentFieldBool `protobuf:"bytes,50,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type SegmentField_RepeatedBoolValue struct {
	RepeatedBoolValue *SegmentFieldRepeatedBool `protobuf:"bytes,51,opt,name=repeated_bool_value,json=repeatedBoolValue,proto3,oneof"`
}

type SegmentField_BlobValue struct {
	BlobValue *SegmentFieldBlob `protobuf:"bytes,60,opt,name=blob_value,json=blobValue,proto3,oneof"`
}

type SegmentField_RepeatedBlobValue struct {
	RepeatedBlobValue *SegmentFieldRepeatedBlob `protobuf:"bytes,61,opt,name=repeated_blob_value,json=repeatedBlobValue,proto3,oneof"`
}

type SegmentField_RangeIntValue struct {
	RangeIntValue *SegmentFieldRangeInt `protobuf:"bytes,70,opt,name=range_int_value,json=rangeIntValue,proto3,oneof"`
}

type SegmentField_RepeatedRangeIntValue struct {
	RepeatedRangeIntValue *SegmentFieldRepeatedRangeInt `protobuf:"bytes,71,opt,name=repeated_range_int_value,json=repeatedRangeIntValue,proto3,oneof"`
}

type SegmentField_RangeFloatValue struct {
	RangeFloatValue *SegmentFieldRangeFloat `protobuf:"bytes,80,opt,name=range_float_value,json=rangeFloatValue,proto3,oneof"`
}

type SegmentField_RepeatedRangeFloatValue struct {
	RepeatedRangeFloatValue *SegmentFieldRepeatedRangeFloat `protobuf:"bytes,81,opt,name=repeated_range_float_value,json=repeatedRangeFloatValue,proto3,oneof"`
}

type SegmentField_GeoPointValue struct {
	GeoPointValue *SegmentFieldGeoPoint `protobuf:"bytes,90,opt,name=geo_point_value,json=geoPointValue,proto3,oneof"`
}

type SegmentField_RepeatedGeoPointValue struct {
	RepeatedGeoPointValue *SegmentFieldRepeatedGeoPoint `protobuf:"bytes,91,opt,name=repeated_geo_point_value,json=repeatedGeoPointValue,proto3,oneof"`
}

type SegmentField_GeoRectValue struct {
	GeoRectValue *SegmentFieldGeoRect `protobuf:"bytes,100,opt,name=geo_rect_value,json=geoRectValue,proto3,oneof"`
}

type SegmentField_RepeatedGeoRectValue struct {
	RepeatedGeoRectValue *SegmentFieldRepeatedGeoRect `protobuf:"bytes,101,opt,name=repeated_geo_rect_value,json=repeatedGeoRectValue,proto3,oneof"`
}

func (*SegmentField_StringValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedStringValue) isSegmentField_Value() {}

func (*SegmentField_IntValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedIntValue) isSegmentField_Value() {}

func (*SegmentField_UintValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedUintValue) isSegmentField_Value() {}

func (*SegmentField_FloatValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedFloatValue) isSegmentField_Value() {}

func (*SegmentField_BoolValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedBoolValue) isSegmentField_Value() {}

func (*SegmentField_BlobValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedBlobValue) isSegmentField_Value() {}

func (*SegmentField_RangeIntValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedRangeIntValue) isSegmentField_Value() {}

func (*SegmentField_RangeFloatValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedRangeFloatValue) isSegmentField_Value() {}

func (*SegmentField_GeoPointValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedGeoPointValue) isSegmentField_Value() {}

func (*SegmentField_GeoRectValue) isSegmentField_Value() {}

func (*SegmentField_RepeatedGeoRectValue) isSegmentField_Value() {}

type SegmentFieldString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldString) Reset() {
	*x = SegmentFieldString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldString) ProtoMessage() {}

func (x *SegmentFieldString) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldString.ProtoReflect.Descriptor instead.
func (*SegmentFieldString) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{2}
}

func (x *SegmentFieldString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SegmentFieldRepeatedString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedString) Reset() {
	*x = SegmentFieldRepeatedString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedString) ProtoMessage() {}

func (x *SegmentFieldRepeatedString) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedString.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedString) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentFieldRepeatedString) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldInt) Reset() {
	*x = SegmentFieldInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldInt) ProtoMessage() {}

func (x *SegmentFieldInt) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldInt.ProtoReflect.Descriptor instead.
func (*SegmentFieldInt) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentFieldInt) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SegmentFieldRepeatedInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []int64 `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedInt) Reset() {
	*x = SegmentFieldRepeatedInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedInt) ProtoMessage() {}

func (x *SegmentFieldRepeatedInt) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedInt.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedInt) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{5}
}

func (x *SegmentFieldRepeatedInt) GetValue() []int64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldUInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldUInt) Reset() {
	*x = SegmentFieldUInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldUInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldUInt) ProtoMessage() {}

func (x *SegmentFieldUInt) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldUInt.ProtoReflect.Descriptor instead.
func (*SegmentFieldUInt) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{6}
}

func (x *SegmentFieldUInt) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SegmentFieldRepeatedUInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []uint64 `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedUInt) Reset() {
	*x = SegmentFieldRepeatedUInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedUInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedUInt) ProtoMessage() {}

func (x *SegmentFieldRepeatedUInt) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedUInt.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedUInt) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{7}
}

func (x *SegmentFieldRepeatedUInt) GetValue() []uint64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldFloat) Reset() {
	*x = SegmentFieldFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldFloat) ProtoMessage() {}

func (x *SegmentFieldFloat) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldFloat.ProtoReflect.Descriptor instead.
func (*SegmentFieldFloat) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{8}
}

func (x *SegmentFieldFloat) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SegmentFieldRepeatedFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []float64 `protobuf:"fixed64,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedFloat) Reset() {
	*x = SegmentFieldRepeatedFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedFloat) ProtoMessage() {}

func (x *SegmentFieldRepeatedFloat) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedFloat.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedFloat) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{9}
}

func (x *SegmentFieldRepeatedFloat) GetValue() []float64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldBool) Reset() {
	*x = SegmentFieldBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldBool) ProtoMessage() {}

func (x *SegmentFieldBool) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldBool.ProtoReflect.Descriptor instead.
func (*SegmentFieldBool) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{10}
}

func (x *SegmentFieldBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type SegmentFieldRepeatedBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []bool `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedBool) Reset() {
	*x = SegmentFieldRepeatedBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedBool) ProtoMessage() {}

func (x *SegmentFieldRepeatedBool) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedBool.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedBool) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{11}
}

func (x *SegmentFieldRepeatedBool) GetValue() []bool {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldBlob) Reset() {
	*x = SegmentFieldBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldBlob) ProtoMessage() {}

func (x *SegmentFieldBlob) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldBlob.ProtoReflect.Descriptor instead.
func (*SegmentFieldBlob) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{12}
}

func (x *SegmentFieldBlob) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SegmentFieldRepeatedBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedBlob) Reset() {
	*x = SegmentFieldRepeatedBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedBlob) ProtoMessage() {}

func (x *SegmentFieldRepeatedBlob) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedBlob.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedBlob) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{13}
}

func (x *SegmentFieldRepeatedBlob) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldRangeInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *SegmentFieldRangeInt) Reset() {
	*x = SegmentFieldRangeInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRangeInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRangeInt) ProtoMessage() {}

func (x *SegmentFieldRangeInt) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRangeInt.ProtoReflect.Descriptor instead.
func (*SegmentFieldRangeInt) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{14}
}

func (x *SegmentFieldRangeInt) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SegmentFieldRangeInt) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SegmentFieldRepeatedRangeInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*SegmentFieldRangeInt `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedRangeInt) Reset() {
	*x = SegmentFieldRepeatedRangeInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedRangeInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedRangeInt) ProtoMessage() {}

func (x *SegmentFieldRepeatedRangeInt) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedRangeInt.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedRangeInt) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{15}
}

func (x *SegmentFieldRepeatedRangeInt) GetValue() []*SegmentFieldRangeInt {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldRangeFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *SegmentFieldRangeFloat) Reset() {
	*x = SegmentFieldRangeFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRangeFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRangeFloat) ProtoMessage() {}

func (x *SegmentFieldRangeFloat) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRangeFloat.ProtoReflect.Descriptor instead.
func (*SegmentFieldRangeFloat) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{16}
}

func (x *SegmentFieldRangeFloat) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SegmentFieldRangeFloat) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SegmentFieldRepeatedRangeFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*SegmentFieldRangeFloat `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedRangeFloat) Reset() {
	*x = SegmentFieldRepeatedRangeFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedRangeFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedRangeFloat) ProtoMessage() {}

func (x *SegmentFieldRepeatedRangeFloat) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedRangeFloat.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedRangeFloat) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{17}
}

func (x *SegmentFieldRepeatedRangeFloat) GetValue() []*SegmentFieldRangeFloat {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldGeoPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *SegmentFieldGeoPoint) Reset() {
	*x = SegmentFieldGeoPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldGeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldGeoPoint) ProtoMessage() {}

func (x *SegmentFieldGeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldGeoPoint.ProtoReflect.Descriptor instead.
func (*SegmentFieldGeoPoint) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{18}
}

func (x *SegmentFieldGeoPoint) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SegmentFieldGeoPoint) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SegmentFieldRepeatedGeoPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*SegmentFieldGeoPoint `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedGeoPoint) Reset() {
	*x = SegmentFieldRepeatedGeoPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedGeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedGeoPoint) ProtoMessage() {}

func (x *SegmentFieldRepeatedGeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedGeoPoint.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedGeoPoint) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{19}
}

func (x *SegmentFieldRepeatedGeoPoint) GetValue() []*SegmentFieldGeoPoint {
	if x != nil {
		return x.Value
	}
	return nil
}

type SegmentFieldGeoRect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopLeft     *SegmentFieldGeoPoint `protobuf:"bytes,1,opt,name=top_left,json=topLeft,proto3" json:"top_left,omitempty"`
	BottomRight *SegmentFieldGeoPoint `protobuf:"bytes,2,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"`
}

func (x *SegmentFieldGeoRect) Reset() {
	*x = SegmentFieldGeoRect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldGeoRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldGeoRect) ProtoMessage() {}

func (x *SegmentFieldGeoRect) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldGeoRect.ProtoReflect.Descriptor instead.
func (*SegmentFieldGeoRect) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{20}
}

func (x *SegmentFieldGeoRect) GetTopLeft() *SegmentFieldGeoPoint {
	if x != nil {
		return x.TopLeft
	}
	return nil
}

func (x *SegmentFieldGeoRect) GetBottomRight() *SegmentFieldGeoPoint {
	if x != nil {
		return x.BottomRight
	}
	return nil
}

type SegmentFieldRepeatedGeoRect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*SegmentFieldGeoRect `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *SegmentFieldRepeatedGeoRect) Reset() {
	*x = SegmentFieldRepeatedGeoRect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFieldRepeatedGeoRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFieldRepeatedGeoRect) ProtoMessage() {}

func (x *SegmentFieldRepeatedGeoRect) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFieldRepeatedGeoRect.ProtoReflect.Descriptor instead.
func (*SegmentFieldRepeatedGeoRect) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{21}
}

func (x *SegmentFieldRepeatedGeoRect) GetValue() []*SegmentFieldGeoRect {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index   string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Segment *Segment `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
}

func (x *PutSegmentRequest) Reset() {
	*x = PutSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSegmentRequest) ProtoMessage() {}

func (x *PutSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSegmentRequest.ProtoReflect.Descriptor instead.
func (*PutSegmentRequest) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{22}
}

func (x *PutSegmentRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *PutSegmentRequest) GetSegment() *Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

type PutSegmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutSegmentResponse) Reset() {
	*x = PutSegmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSegmentResponse) ProtoMessage() {}

func (x *PutSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSegmentResponse.ProtoReflect.Descriptor instead.
func (*PutSegmentResponse) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{23}
}

type GetSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index string        `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Key   *SegmentField `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // Lookup on index primary key
}

func (x *GetSegmentRequest) Reset() {
	*x = GetSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentRequest) ProtoMessage() {}

func (x *GetSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentRequest) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{24}
}

func (x *GetSegmentRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *GetSegmentRequest) GetKey() *SegmentField {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetSegmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segment *Segment `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
}

func (x *GetSegmentResponse) Reset() {
	*x = GetSegmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentResponse) ProtoMessage() {}

func (x *GetSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentResponse) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{25}
}

func (x *GetSegmentResponse) GetSegment() *Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

type DeleteSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index string        `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Key   *SegmentField `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // Lookup on index primary key
}

func (x *DeleteSegmentRequest) Reset() {
	*x = DeleteSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentRequest) ProtoMessage() {}

func (x *DeleteSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteSegmentRequest) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteSegmentRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *DeleteSegmentRequest) GetKey() *SegmentField {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteSegmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSegmentResponse) Reset() {
	*x = DeleteSegmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentResponse) ProtoMessage() {}

func (x *DeleteSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteSegmentResponse) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{27}
}

var File_segment_proto protoreflect.FileDescriptor

var file_segment_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x34, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x29, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0xff, 0x0b, 0x0a, 0x0c, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x3c, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00,
	0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x55, 0x0a,
	0x15, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x13, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4c, 0x0a, 0x12, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x75, 0x69, 0x6e, 0x74, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x55, 0x49,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x75, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x4f, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x69, 0x6e, 0x74,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x55, 0x49, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x11, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x55, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x39, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x48, 0x00, 0x52,
	0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x52, 0x0a, 0x14, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x29, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x48, 0x00, 0x52, 0x12, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x36, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x32, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4f, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x33,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x6f, 0x6f, 0x6c, 0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x62,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42,
	0x6c, 0x6f, 0x62, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x4f, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f,
	0x62, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x3d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x48, 0x00, 0x52, 0x11,
	0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x43, 0x0a, 0x0f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x46, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x49, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x5c, 0x0a, 0x18, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x47, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x15, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x49, 0x0a, 0x11, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x66, 0x6c,
	0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x50, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x48, 0x00, 0x52, 0x0f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x62, 0x0a, 0x1a, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x51, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x48, 0x00, 0x52, 0x17, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x67, 0x65, 0x6f, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47,
	0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x65, 0x6f, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x5c, 0x0a, 0x18, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6f, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x5b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x15, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x67, 0x65, 0x6f, 0x5f, 0x72, 0x65,
	0x63, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x47, 0x65, 0x6f, 0x52, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x65, 0x6f, 0x52,
	0x65, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x59, 0x0a, 0x17, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6f, 0x5f, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x47, 0x65, 0x6f, 0x52, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x14, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x47, 0x65, 0x6f, 0x52, 0x65, 0x63, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x12,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x1a, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x17, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x55, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x30, 0x0a, 0x18, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x55, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a,
	0x19, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x28, 0x0a, 0x10, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a, 0x18, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x10,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x6c, 0x6f, 0x62,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a, 0x18, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x6c,
	0x6f, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x0a, 0x14, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d,
	0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6d, 0x61, 0x78, 0x22, 0x4f, 0x0a, 0x1c, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x49, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x16, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x6d, 0x61, 0x78, 0x22, 0x53, 0x0a, 0x1e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x14, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x4f, 0x0a, 0x1c,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47, 0x65,
	0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x89, 0x01,
	0x0a, 0x13, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47, 0x65,
	0x6f, 0x52, 0x65, 0x63, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x65, 0x66,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x3c, 0x0a, 0x0c, 0x62,
	0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x62, 0x6f,
	0x74, 0x74, 0x6f, 0x6d, 0x52, 0x69, 0x67, 0x68, 0x74, 0x22, 0x4d, 0x0a, 0x1b, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x47, 0x65, 0x6f, 0x52, 0x65, 0x63, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47, 0x65, 0x6f, 0x52, 0x65, 0x63,
	0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x51, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x50,
	0x75, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x4e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x23, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x3c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x51, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x23, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x71, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_segment_proto_rawDescOnce sync.Once
	file_segment_proto_rawDescData = file_segment_proto_rawDesc
)

func file_segment_proto_rawDescGZIP() []byte {
	file_segment_proto_rawDescOnce.Do(func() {
		file_segment_proto_rawDescData = protoimpl.X.CompressGZIP(file_segment_proto_rawDescData)
	})
	return file_segment_proto_rawDescData
}

var file_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_segment_proto_goTypes = []interface{}{
	(*Segment)(nil),                        // 0: api.Segment
	(*SegmentField)(nil),                   // 1: api.SegmentField
	(*SegmentFieldString)(nil),             // 2: api.SegmentFieldString
	(*SegmentFieldRepeatedString)(nil),     // 3: api.SegmentFieldRepeatedString
	(*SegmentFieldInt)(nil),                // 4: api.SegmentFieldInt
	(*SegmentFieldRepeatedInt)(nil),        // 5: api.SegmentFieldRepeatedInt
	(*SegmentFieldUInt)(nil),               // 6: api.SegmentFieldUInt
	(*SegmentFieldRepeatedUInt)(nil),       // 7: api.SegmentFieldRepeatedUInt
	(*SegmentFieldFloat)(nil),              // 8: api.SegmentFieldFloat
	(*SegmentFieldRepeatedFloat)(nil),      // 9: api.SegmentFieldRepeatedFloat
	(*SegmentFieldBool)(nil),               // 10: api.SegmentFieldBool
	(*SegmentFieldRepeatedBool)(nil),       // 11: api.SegmentFieldRepeatedBool
	(*SegmentFieldBlob)(nil),               // 12: api.SegmentFieldBlob
	(*SegmentFieldRepeatedBlob)(nil),       // 13: api.SegmentFieldRepeatedBlob
	(*SegmentFieldRangeInt)(nil),           // 14: api.SegmentFieldRangeInt
	(*SegmentFieldRepeatedRangeInt)(nil),   // 15: api.SegmentFieldRepeatedRangeInt
	(*SegmentFieldRangeFloat)(nil),         // 16: api.SegmentFieldRangeFloat
	(*SegmentFieldRepeatedRangeFloat)(nil), // 17: api.SegmentFieldRepeatedRangeFloat
	(*SegmentFieldGeoPoint)(nil),           // 18: api.SegmentFieldGeoPoint
	(*SegmentFieldRepeatedGeoPoint)(nil),   // 19: api.SegmentFieldRepeatedGeoPoint
	(*SegmentFieldGeoRect)(nil),            // 20: api.SegmentFieldGeoRect
	(*SegmentFieldRepeatedGeoRect)(nil),    // 21: api.SegmentFieldRepeatedGeoRect
	(*PutSegmentRequest)(nil),              // 22: api.PutSegmentRequest
	(*PutSegmentResponse)(nil),             // 23: api.PutSegmentResponse
	(*GetSegmentRequest)(nil),              // 24: api.GetSegmentRequest
	(*GetSegmentResponse)(nil),             // 25: api.GetSegmentResponse
	(*DeleteSegmentRequest)(nil),           // 26: api.DeleteSegmentRequest
	(*DeleteSegmentResponse)(nil),          // 27: api.DeleteSegmentResponse
}
var file_segment_proto_depIdxs = []int32{
	1,  // 0: api.Segment.fields:type_name -> api.SegmentField
	2,  // 1: api.SegmentField.string_value:type_name -> api.SegmentFieldString
	3,  // 2: api.SegmentField.repeated_string_value:type_name -> api.SegmentFieldRepeatedString
	4,  // 3: api.SegmentField.int_value:type_name -> api.SegmentFieldInt
	5,  // 4: api.SegmentField.repeated_int_value:type_name -> api.SegmentFieldRepeatedInt
	6,  // 5: api.SegmentField.uint_value:type_name -> api.SegmentFieldUInt
	7,  // 6: api.SegmentField.repeated_uint_value:type_name -> api.SegmentFieldRepeatedUInt
	8,  // 7: api.SegmentField.float_value:type_name -> api.SegmentFieldFloat
	9,  // 8: api.SegmentField.repeated_float_value:type_name -> api.SegmentFieldRepeatedFloat
	10, // 9: api.SegmentField.bool_value:type_name -> api.SegmentFieldBool
	11, // 10: api.SegmentField.repeated_bool_value:type_name -> api.SegmentFieldRepeatedBool
	12, // 11: api.SegmentField.blob_value:type_name -> api.SegmentFieldBlob
	13, // 12: api.SegmentField.repeated_blob_value:type_name -> api.SegmentFieldRepeatedBlob
	14, // 13: api.SegmentField.range_int_value:type_name -> api.SegmentFieldRangeInt
	15, // 14: api.SegmentField.repeated_range_int_value:type_name -> api.SegmentFieldRepeatedRangeInt
	16, // 15: api.SegmentField.range_float_value:type_name -> api.SegmentFieldRangeFloat
	17, // 16: api.SegmentField.repeated_range_float_value:type_name -> api.SegmentFieldRepeatedRangeFloat
	18, // 17: api.SegmentField.geo_point_value:type_name -> api.SegmentFieldGeoPoint
	19, // 18: api.SegmentField.repeated_geo_point_value:type_name -> api.SegmentFieldRepeatedGeoPoint
	20, // 19: api.SegmentField.geo_rect_value:type_name -> api.SegmentFieldGeoRect
	21, // 20: api.SegmentField.repeated_geo_rect_value:type_name -> api.SegmentFieldRepeatedGeoRect
	14, // 21: api.SegmentFieldRepeatedRangeInt.value:type_name -> api.SegmentFieldRangeInt
	16, // 22: api.SegmentFieldRepeatedRangeFloat.value:type_name -> api.SegmentFieldRangeFloat
	18, // 23: api.SegmentFieldRepeatedGeoPoint.value:type_name -> api.SegmentFieldGeoPoint
	18, // 24: api.SegmentFieldGeoRect.top_left:type_name -> api.SegmentFieldGeoPoint
	18, // 25: api.SegmentFieldGeoRect.bottom_right:type_name -> api.SegmentFieldGeoPoint
	20, // 26: api.SegmentFieldRepeatedGeoRect.value:type_name -> api.SegmentFieldGeoRect
	0,  // 27: api.PutSegmentRequest.segment:type_name -> api.Segment
	1,  // 28: api.GetSegmentRequest.key:type_name -> api.SegmentField
	0,  // 29: api.GetSegmentResponse.segment:type_name -> api.Segment
	1,  // 30: api.DeleteSegmentRequest.key:type_name -> api.SegmentField
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_segment_proto_init() }
func file_segment_proto_init() {
	if File_segment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_segment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldUInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedUInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRangeInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedRangeInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRangeFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedRangeFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldGeoPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedGeoPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldGeoRect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFieldRepeatedGeoRect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutSegmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSegmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSegmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_segment_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SegmentField_StringValue)(nil),
		(*SegmentField_RepeatedStringValue)(nil),
		(*SegmentField_IntValue)(nil),
		(*SegmentField_RepeatedIntValue)(nil),
		(*SegmentField_UintValue)(nil),
		(*SegmentField_RepeatedUintValue)(nil),
		(*SegmentField_FloatValue)(nil),
		(*SegmentField_RepeatedFloatValue)(nil),
		(*SegmentField_BoolValue)(nil),
		(*SegmentField_RepeatedBoolValue)(nil),
		(*SegmentField_BlobValue)(nil),
		(*SegmentField_RepeatedBlobValue)(nil),
		(*SegmentField_RangeIntValue)(nil),
		(*SegmentField_RepeatedRangeIntValue)(nil),
		(*SegmentField_RangeFloatValue)(nil),
		(*SegmentField_RepeatedRangeFloatValue)(nil),
		(*SegmentField_GeoPointValue)(nil),
		(*SegmentField_RepeatedGeoPointValue)(nil),
		(*SegmentField_GeoRectValue)(nil),
		(*SegmentField_RepeatedGeoRectValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_segment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_segment_proto_goTypes,
		DependencyIndexes: file_segment_proto_depIdxs,
		MessageInfos:      file_segment_proto_msgTypes,
	}.Build()
	File_segment_proto = out.File
	file_segment_proto_rawDesc = nil
	file_segment_proto_goTypes = nil
	file_segment_proto_depIdxs = nil
}
